name: proy_aqa
description: Proyecto AQa - Plataforma de Distribución de Agua en Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  http: any
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  flutter_local_notifications_platform_interface: ^8.0.0
  geolocator: ^13.0.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.1.5
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  firebase_messaging_web: ^3.5.18
