name: proy_aqa
description: Proyecto AQa - Plataforma de Distribución de Agua en Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2  # Adding this line
  provider: ^6.0.5
  http: any  # I see you're already using http
  firebase_messaging: ^14.1.0
  flutter_local_notifications: ^9.7.0
  geolocator: ^9.0.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
